meta_product_name: "Wild Cities - A new way of exploring a city"
meta_title: "Wild Cities - Be curious, travel différent :)"
meta_description: "The alternative way of exploring a city"
meta_image: "background-fb.png"                       # should exist in `app/assets/images/`
twitter_account: "@CitiesWild"   # required for Twitter Cards
